// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xthijrmlfcarkkehrwdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aGlqcm1sZmNhcmtrZWhyd2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTc1NjMsImV4cCI6MjA2MDEzMzU2M30.EPdV7w_X-2Y5viXCu9v_zUL3k6tugvh-Ls-Wpw06wPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);